Repository H4ckSpace/HacktoberFest24, pull requests merged in 2024-10, with the labels that each got.

#2 TeleTwilio is a Telegram bot Script that allows users to send text m…
  TeleTwilio/LICENSE
  TeleTwilio/README.md
  TeleTwilio/configs/firebase.py
  TeleTwilio/configs/telegram.py
  TeleTwilio/configs/twilioconf.py
  TeleTwilio/main.py
  TeleTwilio/modules/ftwilio.py
  TeleTwilio/requirements.txt
  TeleTwilio/runtime.txt
  TeleTwilio/templates/start.py
Labels: hacktoberfest-accepted, hacktoberfest

#3 New ML Algorithms for Hactoberfest
  ML Algorithms/naive_bayes.py
  ML Algorithms/random_forest_classifier.py
Labels: hacktoberfest-accepted, hacktoberfest

#8 Python script to take useful information from passport.
  Utility Scripts/passport_scrapper.py
Labels: documentation, enhancement, hacktoberfest-accepted, hacktoberfest

#9 GitHubProfileFinder
  GitFindr/GitHubProfileFinder.py
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#10 Added dbscan_clustering algo
  ML Algorithms/dbscan_clustering.py
Labels: hacktoberfest-accepted, hacktoberfest

#12 Add passphraseGenerator.py and phrases.csv for generating random pass…
  encryption/RSA-Encryption.py
  encryption/passphraseGenerator.py
  encryption/phrases.csv
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#13 Add YT-VideoDL.py script for downloading YouTube videos
  Utility Scripts/YT-VideoDL.py
Labels: documentation, enhancement, hacktoberfest-accepted, hacktoberfest

#14 Add Weather app main.py script for retrieving weather data and sending…
  Weather app/main.py
Labels: hacktoberfest-accepted, hacktoberfest

#22 flag.txt
  ctfHackTheBoo/Mathematricks/flag.txt
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#20 Create README.md
  GitFindr/README.md
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#19 WebsiteStatusChecker
  WebPulse 360/WebsiteStatusChecker.py
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#16 WordlGame
  WordleGame/README.md
  WordleGame/client/.gitignore
  WordleGame/client/README.md
  WordleGame/client/eslint.config.js
  WordleGame/client/index.html
  WordleGame/client/package-lock.json
  WordleGame/client/package.json
  WordleGame/client/public/vite.svg
  WordleGame/client/src/App.jsx
  WordleGame/client/src/assets/react.svg
  WordleGame/client/src/index.css
  WordleGame/client/src/main.jsx
  WordleGame/client/src/pages/Home/Home.css
  WordleGame/client/src/pages/Home/Home.jsx
  WordleGame/client/vite.config.js
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#17 Internet Speed Test Application
  Internet Speed/NetFire.py
  Internet Speed/README.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#18 NextGenDomain.py
  NextGenDomains/NextGenDomain.py
Labels: documentation, enhancement, hacktoberfest-accepted, hacktoberfest

#25 create input cells, select target word randomly
  WordleGame/client/src/pages/Home/Home.jsx
Labels: hacktoberfest-accepted, hacktoberfest

#24 Add files via upload
  A_Finder.py
Labels: hacktoberfest-accepted, hacktoberfest

#27 Add files via upload
  tic_tac_toe.py
  tic_tac_toe_vs_MAC.py
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#37 SVM Classifier Training and Decision Tree Code Refactoring
  ML Algorithms/DecisionTree.py
  ML Algorithms/SupportVectorMachine(SVM).py
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#35 Convert Excel data to csv file
  xlxs_csv/Documentation
  xlxs_csv/script.py
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#34 Hamming Code
  Hamming Code/Readme.md
  Hamming Code/hamming.py
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#38 CasinoGame
  CasinoGame/Readme.md
  CasinoGame/pythonprojrct.py
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#39 Tik-Tac-Ton
  tik_tac_ton/.trunk/.gitignore
  tik_tac_ton/.trunk/configs/.markdownlint.yaml
  tik_tac_ton/.trunk/trunk.yaml
  tik_tac_ton/README.md
  tik_tac_ton/index.html
  tik_tac_ton/sampl.js
  tik_tac_ton/style.css
  tik_tak_ton/README.md
Labels: hacktoberfest-accepted, hacktoberfest

#40 solver.py
  ctfHackTheBoo/Mathematricks/solver.py
Labels: hacktoberfest-accepted, hacktoberfest

#31 Created morse_code.py
  Morse_Code/morse_code.py
Labels: hacktoberfest-accepted, hacktoberfest

#42 Add logic for succes and show alert
  WordleGame/client/src/pages/Home/Home.jsx
Labels: hacktoberfest-accepted, hacktoberfest

#43 Random_Password_Generator
  Random_Password_Generator/index.html
  Random_Password_Generator/script.js
  Random_Password_Generator/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#41 Random_Password_Generator
  index.html
  script.js
  style.css
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#33 Odd_or_Even
  Utility Scripts/Odd_even.py
Labels: enhancement, hacktoberfest-accepted, hacktoberfest
